### ISSUE TITLE
Seperate Audio Decoders/Encoders and Audio Utils.

### ISSUE THREAD

**Issue by zet4** [tuffy/python-audio-tools#61]
I don't really believe its right to maintain the entire thing in single package, this library (or rather its encoding and decoding parts) could be used in other projects and pulling the 20 or so other scripts and UI seems like too much.

But that's just my opinion, feel free to ignore it.

**Comment by tuffy** [comment]
Python's distutils does offer a "setup.py install_lib" option which is supposed to install only the Python libraries and C extensions, and not any executable scripts.

I'd prefer not to make people download the scripts separately because they're not much use on their own and make up a fairly small percentage of the overall code.
